### ISSUE TITLE
swagger-gradle-plugin and io.franzbecker.gradle-lombok don't play nicely together

### ISSUE THREAD

**Issue by rherrick** [franzbecker/gradle-lombok#47] opened 2018-08-02 03:22 UTC
I have a Gradle build in which I'm trying to use both of these plugins. You can [see the project and try the build yourself](https://bitbucket.org/rherrick/xchange) to see the issue. I'm also including a version of [**build.gradle** with the Lombok plugin working](https://github.com/franzbecker/gradle-lombok/files/2251953/lombok-build.gradle.txt) and [another with the Swagger plugin working](https://github.com/franzbecker/gradle-lombok/files/2251952/swagger-build.gradle.txt).

The problem is that, with both of these plugins configured in the **build.gradle**, I get the following error:

```bash
$ ./gradlew jar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'xchange'.
> Cannot change dependencies of configuration ':compileOnly' after it has been included in dependency resolution.
```

I've included the [full stack trace as well](https://github.com/franzbecker/gradle-lombok/files/2251951/error.log).

Note that this occurs during the evaluation phase, so it actually breaks the IDE integration as well.

It's definitely the interaction of these two plugins because, if I comment out **swagger-gradle-plugin**, the project builds fine (of course, I can't use any of the Swagger plugin tasks). If I comment out **io.franzbecker.gradle-lombok** and manually patch in what that plugin does (add Lombok dependencies for **annotationProcessor**, **compileOnly**, and **testCompile**), the project builds fine (of course, I can't use any of the Lombok plugin tasks).

I'm actually submitting this issue both here and on the Swagger plugin project since I'm really not sure which of the two is the problem (this is [issue #98 in the Swagger plugin issues](https://github.com/gigaSproule/swagger-gradle-plugin/issues/98)). The failure is clearly coming in the Lombok plugin code, but it seems like the Swagger plugin is doing something that affects the **compileOnly** configuration, since the Lombok plugin doesn't fail without that. Wherever the root cause is, it's likely that it will affect other plugins down the line as well.

**Comment by gigaSproule** [comment] 2018-08-03 06:47
Hey @franzbecker, I'm the maintainer of the other plugin. It's obvious what is happening, my plugin requires going through all of the dependencies and then this plugin is trying to add a dependency. Is there a reason why you're adding a dependency in the `afterEvaluate`? I'm not seeing any logic in there that requires knowing what has happened before?

I'm also looking into how `afterEvaluate` blocks can be forced into an order.

**Comment by franzbecker** [comment] 2018-08-06 21:37
Hey there! Thanks for the feedback and sorry for the late reply - I was on vacation and don't have too much time right now. As far as I can remember the `afterEvaluate` was necessary for getting the version from the plugin configuration so that the user can specify which Lombok version to use like this:
```
lombok {
    version = "1.16.20"
}
```
So as far as I remember the project needs to be evaluated first before I can read the configuration. I built it when it was Gradle 2.x and maybe the mechanisms have changed a bit since then. Would you have some hints?

**Comment by gigaSproule** [comment] 2018-08-06 22:03
I'd expect what you have already to work. Maybe worth a try just in case? I only created mine from 3.x, so maybe they did change something and I'm also unaware of it.

**Comment by gigaSproule** [comment] 2018-08-12 07:37
Managed to find some time to look at this. I believe this is being caused by an older version of my plugin. So assuming that's the case (and not some weird Gradle graph organisation luck), this isn't an issue. Feel free to close this and if anything changes, I'll comment here.

**Comment by franzbecker** [comment] 2018-08-13 06:41
Okay, thanks for the update and your time to look at it :)

**Closed as completed by franzbecker** 2018-08-13 06:41 UTC

**Comment by rherrick** [comment] 2018-08-28 15:00
Sorry I missed these back and forth messages, I get too many emails and they got lost amongst all the junk.

I really don't think this is related to using an old version of the Swagger plugin. Or at least I'm using the newest version available on plugins.gradle.org, which is 1.0.4 (I even tried 1.0.5, which is what's currently in the dev repo, but that can't be found).

So I attached the simplest project I could define. It includes only the Swagger plugin v1.0.4, the Lombok plugin v1.14, and the java plugin. 

* [build.txt](https://github.com/franzbecker/gradle-lombok/files/2328577/build.txt)
* [settings.txt](https://github.com/franzbecker/gradle-lombok/files/2328536/settings.txt)

```gradle
plugins {
    id "com.benjaminsproule.swagger" version "1.0.4"
    id "io.franzbecker.gradle-lombok" version "1.14"
    id "java"
}

repositories {
    jcenter()
}

group = "plugins"
version = "0.0.1-SNAPSHOT"

lombok {
    version = "1.18.2"
    sha256 = "f13db210efa2092a58bb7befce58ffa502e5fefc5e1099f45007074008756bc0"
}

dependencies {
    implementation "io.springfox:springfox-swagger2:2.9.2"
    implementation "io.springfox:springfox-swagger-ui:2.9.2"
}
```

Make an empty folder, run **gradle init** (I'm running Gradle 4.9), and replace the default **build.gradle** with this **build.txt** file (you can replace **settings.gradle** as well, but it's not really doing anything). Then try to run any Gradle task:

```bash
-> % ./gradlew tasks

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'test'.
> Cannot change dependencies of configuration ':compileOnly' after it has been included in dependency resolution.

...
BUILD FAILED in 0s
```

This has the newest available version of each plugin and nothing else (besides the obvious requirement of the **java** plugin) to interfere. If I comment out the Lombok plugin and configuration, it works fine. If I comment out the Swagger plugin, it works fine. The two together... it doesn't work fine.

**Comment by rherrick** [comment] 2018-08-28 19:20
Just a little extra stuff I did that may be helpful. I actually reduced the **build.gradle** to nothing other than the **plugins** element:

```gradle
plugins {
    id "com.benjaminsproule.swagger" version "1.0.4"
    id "io.franzbecker.gradle-lombok" version "1.14"
    id "java"
}
```

Even the simplest tasks fail:

```bash
-> % ./gradlew clean

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'test'.
> Cannot change dependencies of configuration ':compileOnly' after it has been included in dependency resolution.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
```

If I comment out either of the Lombok or Swagger plugins it works.

Just for fun, I tried this same build on a totally green server: I run sites on the server but all builds there are done on a Jenkins instance, so I have no build artifacts or tools under my home folder. I installed sdkman then gradle, meaning I got v4.10 which dropped today. I ran **gradle init**, modified **build.gradle** with just the **plugins** element, and ran **./gradlew clean**. Same error.

Worth noting: all of the builds I've been doing are with the latest JDK 8 (probably 171 when I started, 181 now) on OSX. That last build I mentioned was on Ubuntu server 18.04.

Please let me know if I can provide any other info or test anything out to fix this issue. Thanks!
